### ISSUE TITLE
Bring back the blinking nodes, please!

### ISSUE THREAD

**Issue by Voxxel** [Shushuda/Mappy-Continued#3]
Hi there and thank you very much for your work on Mappy!

Mappy is my all-time favorite minimap addon even though its best feature has been cropped years ago:  -The blinking (flashing) mining/herb/fishing nodes. That was the key feature that made Mappy so unique among the other tons of minimap addons a decade ago. I'm not sure if you can remember this feature but I remember Mundocani used 2 node icons of the same pin texture (1 colored to yellow and 1 colored to blue) and used them continuously switching several times in a second to make a blinking effect to display flashing nodes on the minimap. This draws attention of a human eye a lot more farther of the screen and therefore we didn't miss any nodes around. The addon was once a gatherers' dream. 

The tickable option is called: ### "Flash gathering Nodes" in the options. It was a brilliant idea indeed. However somewhere in the last decade the actual maintainer of Mappy have cut this feature off. :( 

Anyhow, Mappy still looks good and stylish but it would be a miracle if you could restore the original blinking nodes to it. Would you please check if the feature could return in 10.x ?

Either way, thank you for your hard work!

**Comment by Shushuda** [comment]
I've actually fixed this feature already!

I've fixed a few features that were broken for a few years, including the coords, profile selection (dropdown menus were broken for a while) and **gathering nodes blinking and/or being larger**.

It works on my end in the prepatch. Since DF, WoW is using separate graphics for fish, herbs and mining nodes, so I've reused these. I can add an option to use pre-DF graphics (the same dot for all node types), if this is what you want. But the feature itself is already fixed and working, it just uses new art now ^^

**Comment by Shushuda** [comment]
This is how they look now:

Normal:
![Normal](https://i.imgur.com/UV2dVw7.png)

Blinking normal:
![Blinking Normal](https://i.imgur.com/lhqvthv.png)

Large:
![Large](https://i.imgur.com/qYVAVJj.png)

Blinking large:
![Blinking large](https://i.imgur.com/u4LU89H.png)

**Comment by Shushuda** [comment]
And a gif example in-game:

![GIF nodes blinking](https://i.imgur.com/oIn73x2.gif)

**Comment by Shushuda** [comment]
Btw, I've uploaded a release. This will land on CurseForge, hopefully soon, in a new project "Mappy Continued". Please let me know what you think about this release.

**Comment by Voxxel** [comment]
Wow! Just wow! 
Pretty nice work, I still can't believe you brought it back! <3 

Still can't find it on CF so I just tried it from here and it looks pretty good already! 
One thing I noticed during the test, the gathering nodes get appeared only when the character gets very close to them. The range is way too short. Compared to rare mob icons or battle-pet icons the gathering nodes are visible only from halfway of them or even less. I don't know if there's anything you can do about it or it's stock wow but it's somewhat annoying especially when flying over a field and have to turn back continuously because the nodes just appear when you fly over it. First I thought it's a latency issue but if it was it had to be the same with other minimap icons too but they're good.

The special gathering icons aren't an issue for me, but they're surely way too small. The option to enlarge nodes could enlarge them a bit more.

Once again I can't thank you enough for reviving this masterpiece. God bless you m8!

**Comment by Shushuda** [comment]
I've uploaded the project to CF, but it's still under review. Their next work day is on Sunday (afair) so the earliest the project will arrive there is next week.

Heh, I couldn't abandon this addon, it's too good! Thankfully I've started learning Lua and addon writing a few weeks ago, when creating my own addon DragonSpeedway, so I had enough knowledge to fix this one by the time prepatch came. And the original code is written very cleanly, which really helped. I'm a Python dev by trade, which kind of contributes to my hate of unclean code. Mappy was written very cleanly and neatly, Mundocani did a great job.

I've checked this just now with the stock minimap and it's definitely Blizzard's fault. The gathering node range must have gotten shorter in prepatch.

I've checked with fishing nodes and I see that I need to get much closer for the actual ingame model of the node to spawn. When it spawns, the icon appears on the minimap instantly. When I move away, the range is longer. The ingame node model unloads at a greater range.

So this seems like an issue with model loading ingame. Nodes are requiring a much shorter range from player to actually render. Weird issue, I don't remember it happening on Beta.

Hmm, I'm not sure if I can even enlarge them more. The addon works by overwriting the stock texture map for those icons. It doesn't overwrite individual icons, but the whole map that contains all of them at once. I've tried to make them as big as the empty space around them, but it's Blizzard that's shrinking them so harshly when they're actually placed on the minimap.

I think a dot would help just because it has less negative space in that 32x32 pixel square that holds the icon texture. I might add this option anyway to help with visibility.

**Comment by Voxxel** [comment]
-Ok, I'll keep looking forward to the CF project. 
-So the range thing is set, we have to live with it or they may revert it in the upcoming DF retail. 
-Don't worry about enlarging them even more then, maybe the original fat dot node texture will do the job anyway. I hope you can make that to flashing too.
-I've started learning Lua and addon writing a few weeks ago_ - is it hard to understand? In early 2000s I learned a language to create addons (mods) for the original Medal of Honor PC game and it went fine. I tried it with WoW Lua several times already but I couldn't get used to it, still. Can you recommend a good web guide for beginners please?
Thank you very much!

**Comment by Shushuda** [comment]
I will make these dots flashing, don't worry.

It's a bit hard to answer if it was hard, tbf. Depends on your experiences. I'm working as a software dev, I write in Python with smaller dabbles into Bash scripting, I also wrote a few Ansible playbooks. My job focuses on cloud networking code, precisely the Neutron component of Openstack. I constantly get tasks where I need to learn an entire new thing with my only documentation being the code itself. Makes you learn how to quickly jump into a new thing and soak as much knowledge as you can.

Lua is actually so stupidly simple that it's harder than Python just because it's so limited. A lot of things I took for granted in Python have to be reimplemented into Lua manually.

One example from Mappy, actually: I had a need to check if a global objects belong to a list of objects. I basically knew that I want to do a line of code only if the object in question was X, Y or Z. In Python, I'd just do a set of X, Y, Z and do a "if object in set" and call it a day. In Lua I had to hack it a bit - I implemented a function that checks if a table has a provided key. Then I had to put X, Y, Z into a pseudo-dict, where the key is the X, Y or Z and the value is true. The function then takes this table and the object and checks if the object is a key in that table. If not, return nil (none). A lot of bother for something that's just built into the language in Python, lmao.

Lua is easy and simple. It's just so simple that it forces you to do weird stuff sometimes that higher level languages would do by themselves.

I recommend going on wowpedia and searching for an article "how to create an addon in 15 minutes". There's also a page that lists all API changes in 10.0.0 patch. And somewhere on wowpedia is a linked repository that holds all UI code for Blizzard stock UI. It's useful for referencing how certain functions or XML frames are built.

Ingame tools are also plenty - /fstack shows you info about the frame you're mousing over and even a path and line of the file that contains its implementation. /dump allows you to dump certain global variables into the chat window. /api is amazing, it's actually an addon made by Blizzard, it holds the current documentation of all globals, events, functions and whatnot. Amazing for searching if something is even possible to use by addons.

I'd suggest going through the "15 minutes" article first, branching out into linked pages that explain in more detail, then picking a subject you want to make an addon about and slowly going through it, searching for info on wowpedia and using ingame tools to check stuff.

Also, looking at other addon's code is a godsend. This is the best source of knowledge by far.

I also remember a series of YT videos someone made about how to make an addon from scratch. It's AMAZING and also fairly recent. I cannot recall the channel name tho, but should be easy to search, that series is looong.

**Comment by Shushuda** [comment]
I've just remembered this website too:

https://wow.tools/

**Comment by Shushuda** [comment]
I've added old dot icons for nodes. I will upload a new release in a moment.

**Comment by Voxxel** [comment]
Thank you for all the information, I'll definitely give it another try on my upcoming holiday. 
Also huge thanks for the work on Mappy too!

**Comment by Shushuda** [comment]
Have fun! Programming is awesome, I bet you'll have lots of fun with it! The rush you get when you create something from nothing is just great.

I'll close this issue for now. Feel free to HMU via CurseForge or here if you have any more questions!
Also, the latest release 4.2.1 fixes a nasty bug with coords in instanced content, so I recommend to update.

**Comment by Shushuda** [comment]
@Voxxel 

It's on CurseForge now - https://www.curseforge.com/wow/addons/mappy-continued

**Comment by Voxxel** [comment]
Nice, thank you!

**Comment by Shushuda** [comment]
@Voxxel 
Another news, this time about the gathering nodes requiring a shorter range to pop in. Apparently there's an issue with asset pop in in the game atm, introduced with the prepatch. This seems connected to ppl experiencing weird stuttering in-game (myself included). That would align with the thing I've noticed before about in-game node models. Just letting you know it's most likely connected, which means it's probably just a bug and should be fixed after Blizz discovers what's going on. I hope. It's weird to experience stuttering on a 3080 and Ryzen 9 lmao

This also happens on beta, btw. I've just checked.
